### PR TITLE
Moved action to use JavaScript

### PR DESCRIPTION
**Pull request by Bullrich**
# Move action to use Javascript

## System changed
- Build process

## Description

Moved the build process to use an already built library so it can use a node image instead of creating a new docker image and downloading node for each execution.

### CODE REVIEW

**Comment by Bullrich** [comment]
@bfercher all the files inside the build directory are auto generated, no need to review those (there are about 10 line changes only)

**Comment by bfercher** [comment]
How much faster will it get with this enhancement?

**Review by bfercher — APPROVED** [review]
👍 can't test

**Comment by Bullrich** [comment]
> How much faster will it get with this enhancement?

Double speed. Won't require to install node in every execution

**Comment by Bullrich** [comment]
@bfercher I lied to you, it went from ~45 seconds to ~5 seconds.

**Pull request merged**
