### PR TITLE
updated packages to latest version

### PR DESCRIPTION
**Pull request by Bullrich**
## System changed
- Dependency versions
- Build

## Description

Updated packages to latest version to support new features available in GitHub Actions, including GitHub enterprise edition (this PR brings that new functionality: https://github.com/actions/toolkit/pull/794).

Some dependency types have changed and they have been updated to the new types.

The `octokitHack.ts` file is no longer needed as that bug has been fixed: https://github.com/actions/toolkit/pull/228

The build directory has been recreated.

### CODE REVIEW

**Comment by Bullrich** [comment]
@bfercher or @rYuuk can you please assign a reviewer and look into this PR? This should provide some new functionalities as it updates the library itself.

**Comment by bfercher** [comment]
@Bullrich is alive 💯

**Comment by Bullrich** [comment]
> @Bullrich is alive 💯

I am alive and on fire 🔥 🔥 🔥

**Comment by Bullrich** [comment]
@bfercher can you look into the ci error? `circleci` seems to not be working anymore. I added a javascript action to run the tests using GitHub actions instead.

**Comment by Bullrich** [comment]
@bfercher I created the exact same PR to the same branch here: https://github.com/Bullrich/Prace.js/pull/1

And `Prace.js` is working, it is reading the file (and failing as intended). Did you modify anything in the configuration of the repository? Should we ignore this and hard merge it?

**Comment by Bullrich** [comment]
Closed as no one is looking at it. I decided to create my own implementation available in https://github.com/Bullrich/Prace.js

**Pull request closed without merging**
